# Copyright (C) 2022 Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: spell
on:
  push:
    branches:
    - master
    paths:
    - '**.md'
  pull_request:
    branches:
    - master

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install pandoc
      run: sudo apt-get install pandoc

    - name: convert .3 man pages to markdown
      run: find docs -name "*.3" -size +40c | sed 's/\.3//' | xargs -t -n1 -I OO pandoc OO.3 -o OO.md

    - name: convert .1 man pages to markdown
      run: find docs -name "*.1" -size +40c | sed 's/\.1//' | xargs -t -n1 -I OO pandoc OO.1 -o OO.md

    - name: setup the custom wordlist
      run: grep '^#W' .github/workflows/spellcheck.yml | sed 's/#W://' >  wordlist.txt

    - name: Check Spelling
      uses: UnicornGlobal/spellcheck-github-actions@master

#W:ACTIVESOCKET
#W:Alessandro
#W:alnum
#W:Altera
#W:ALTSVC
#W:amiga
#W:AmigaOS
#W:AmiSSL
#W:anyauth
#W:anycast
#W:API
#W:APIs
#W:APPCONNECT
#W:archivers
#W:Archos
#W:Arntsen
#W:ascii
#W:asynch
#W:AsynchDNS
#W:auth
#W:autobuild
#W:autobuilds
#W:Autotools
#W:autotools
#W:backend
#W:backends
#W:backoff
#W:backticks
#W:Baratov
#W:BDFL
#W:BearSSL
#W:Benoit
#W:bitmask
#W:bitwise
#W:Björn
#W:Bjørn
#W:bool
#W:boolean
#W:BoringSSL
#W:boringssl
#W:Boukris
#W:Broadcom
#W:brotli
#W:bugfix
#W:bugfixes
#W:buildconf
#W:CDN
#W:CentOS
#W:CERTINFO
#W:Chaffraix
#W:changelog
#W:CharConv
#W:charset
#W:charsets
#W:checksums
#W:CIFS
#W:CLA
#W:CLAs
#W:cleartext
#W:CLI
#W:clientp
#W:cliget
#W:closesocket
#W:CMake
#W:cmake
#W:cmake's
#W:CMakeLists
#W:Comcast
#W:Config
#W:config
#W:conncache
#W:CONNECTCODE
#W:connectdata
#W:COOKIEFILE
#W:CookieInfo
#W:cookiejar
#W:COOKIELIST
#W:CR
#W:CRL
#W:CRLF
#W:crt
#W:crypto
#W:cryptographic
#W:cryptographically
#W:CSEQ
#W:CSeq
#W:CTRL
#W:cURL
#W:CURLcode
#W:CURLH
#W:CURLHSTS
#W:curlimages
#W:CURLINFO
#W:CURLMOPT
#W:CURLOPT
#W:curlrc
#W:CURLU
#W:CURLVERSION
#W:customizable
#W:CUSTOMREQUEST
#W:CVE
#W:CWD
#W:daniel
#W:DEBUGFUNCTION
#W:decrypt
#W:deselectable
#W:detections
#W:dev
#W:devcpp
#W:devtools
#W:dir
#W:distro
#W:distro's
#W:distros
#W:dlist
#W:DLL
#W:DLLs
#W:DNS
#W:dns
#W:DoH
#W:Dudka
#W:Dymond
#W:EBCDIC
#W:EFnet
#W:eg
#W:EHLO
#W:else's
#W:encodings
#W:enctype
#W:Engler
#W:enum
#W:epoll
#W:EPRT
#W:EPSV
#W:ERRNO
#W:errno
#W:ERRORBUFFER
#W:etag
#W:ETag
#W:ETags
#W:exe
#W:extensibility
#W:Falkeborn
#W:Fandrich
#W:Fastly
#W:fcpp
#W:ffi
#W:fiddlings
#W:filesize
#W:filesystem
#W:FILETIME
#W:FLOSS
#W:formpost
#W:formposts
#W:Fortnite
#W:FOSS
#W:FPL
#W:fread
#W:FreeBSD
#W:Frexx
#W:fseek
#W:FTPing
#W:fwrite
#W:gcc
#W:gdb
#W:Gergely
#W:getaddrinfo
#W:gethostname
#W:Getinfo
#W:GETing
#W:getpwuid
#W:Ghedini
#W:Gisle
#W:github
#W:gitter
#W:globbing
#W:gmail
#W:GnuTLS
#W:gnutls
#W:Golemon
#W:GPL
#W:Greear
#W:GSKit
#W:GSS
#W:Guenter
#W:Gunderson
#W:Gustafsson
#W:gzip
#W:Gzipped
#W:gzipped
#W:Hackerone
#W:hackerone
#W:HackerOne's
#W:Hards
#W:Haxx
#W:haxx
#W:HELO
#W:Hoersken
#W:Holme
#W:homebrew
#W:hostname
#W:hostnames
#W:Housley
#W:Hruska
#W:HSTS
#W:hsts
#W:HTC
#W:html
#W:http
#W:HTTPAUTH
#W:httpget
#W:HttpGet
#W:HTTPHEADER
#W:HTTPS
#W:https
#W:Huawei
#W:IDN
#W:IETF
#W:ifdef
#W:ifdefed
#W:Ifdefs
#W:ifdefs
#W:IMAP
#W:imap
#W:IMAPS
#W:imaps
#W:init
#W:interoperates
#W:IoT
#W:IPCXN
#W:ipod
#W:IPv
#W:IRIs
#W:Jakub
#W:Jiri
#W:jo
#W:jq
#W:JSON
#W:json
#W:Julien
#W:Kamil
#W:Kaufmann
#W:keepalive
#W:Keil
#W:Kirei
#W:Knauf
#W:kqueue
#W:Krb
#W:krb
#W:kubernetes
#W:Kuhrt
#W:Largefile
#W:LASTSOCKET
#W:LDAP
#W:ldap
#W:LDAPS
#W:ldaps
#W:LF
#W:libc
#W:libcurl
#W:libcurl's
#W:libcurls
#W:libera
#W:libev
#W:libevent
#W:libidn
#W:libpsl
#W:Libre
#W:libre
#W:LibreSSL
#W:libressl
#W:librtmp
#W:libs
#W:libssh
#W:libSSH
#W:libssh2
#W:libuv
#W:libz
#W:libzstd
#W:linux
#W:localhost
#W:logfile
#W:lookups
#W:LSB
#W:lseek
#W:macdef
#W:macOS
#W:makefiles
#W:malloc
#W:Marek
#W:Mavrogiannopoulos
#W:mbedTLS
#W:Meglio
#W:memdebug
#W:Metalink
#W:Michal
#W:MicroOS
#W:mingw
#W:misconfigured
#W:Mishyn
#W:MITM
#W:mk
#W:Monnerat
#W:MPL
#W:MQTT
#W:mqtt
#W:mqtts
#W:MSB
#W:MSGSENT
#W:mstate
#W:MSVC
#W:MSYS
#W:msys
#W:mTLS
#W:multicwd
#W:MultiSSL
#W:mumbo
#W:mutex
#W:MX
#W:Nagel
#W:NAMELOOKUP
#W:NATs
#W:Necko
#W:netrc
#W:Netware
#W:nghttp
#W:ngtcp
#W:Nikos
#W:nitems
#W:NixOS
#W:NLST
#W:nmemb
#W:NMetware
#W:nocwd
#W:nroff
#W:nslookup
#W:NSS
#W:NTLM
#W:NUM
#W:OAuth
#W:OCSP
#W:Ok
#W:OpenBSD
#W:openldap
#W:Opensocket
#W:OpenSSF
#W:OpenSSF's
#W:OpenSSL
#W:openSUSE
#W:openwall
#W:ORing
#W:Osipov
#W:OSS
#W:pacman
#W:parser's
#W:parsers
#W:PASV
#W:PEM
#W:perl
#W:permafailing
#W:PKGBUILD
#W:pluggable
#W:pollset
#W:POSIX
#W:Postfix
#W:POSTing
#W:POSTs
#W:PowerShell
#W:pre
#W:prebuilt
#W:precompiled
#W:preprocess
#W:preprocessed
#W:preprocessor
#W:Prereq
#W:PRET
#W:PRETRANSFER
#W:pretransfer
#W:printf
#W:printf's
#W:PROXYAUTH
#W:PSL
#W:pthreads
#W:PTR
#W:ptr
#W:QoS
#W:QUIC
#W:Raad
#W:RBS
#W:READFUNCTION
#W:READONLYFILE
#W:rebase
#W:RECV
#W:Redhat
#W:redirections
#W:redirs
#W:redistributable
#W:Referer
#W:referer
#W:repo
#W:RETR
#W:Rikard
#W:ROADMAP
#W:Rockbox
#W:roffit
#W:RTMP
#W:rtmp
#W:RTMPS
#W:RTP
#W:RTSP
#W:rtsp
#W:runtests
#W:runtime
#W:Ruslan
#W:rustls
#W:Sagula
#W:SanDisk
#W:SAS
#W:SASL
#W:Satiro
#W:Schannel
#W:Schindelin
#W:SCP
#W:scp
#W:se
#W:SEB
#W:SEK
#W:selectable
#W:Serv
#W:setopt
#W:SFTP
#W:sftp
#W:sha
#W:singlecwd
#W:Sintonen
#W:sizeof
#W:SLE
#W:slist
#W:sln
#W:SMB
#W:smb
#W:SMBS
#W:smbs
#W:SMTP
#W:smtp
#W:smtps
#W:SMTPS
#W:SNI
#W:SOCKETFUNCTION
#W:socketopen
#W:sockopt
#W:SOCKOPT
#W:Solaris
#W:Soref
#W:SPNEGO
#W:Spotify
#W:src
#W:SRP
#W:SSL
#W:ssl
#W:SSLKEYLOGFILE
#W:sslv
#W:SSLv
#W:SSLVERSION
#W:SSPI
#W:stackoverflow
#W:STARTTLS
#W:STARTTRANSFER
#W:stateful
#W:stderr
#W:stdin
#W:stdout
#W:Steinar
#W:Stenberg
#W:strcpy
#W:struct
#W:structs
#W:Structs
#W:subdirectory
#W:substring
#W:substrings
#W:superset
#W:svc
#W:Svyatoslav
#W:Swisscom
#W:symlink
#W:symlinks
#W:syntaxes
#W:Szakats
#W:TABs
#W:Tatsuhiro
#W:TBD
#W:TCP
#W:tcpdump
#W:TFTP
#W:tftp
#W:TIMERFUNCTION
#W:TLS
#W:tlsv
#W:TODO
#W:Tomtom
#W:toolchains
#W:TrackMemory
#W:Tse
#W:Tsujikawa
#W:TTL
#W:txt
#W:typedef
#W:typedefed
#W:UDP
#W:UI
#W:UID
#W:Unary
#W:uncompress
#W:unencrypted
#W:unix
#W:UnixSockets
#W:Unshare
#W:unsharing
#W:upstreaming
#W:URI
#W:URIs
#W:URL's
#W:urlencoded
#W:urlget
#W:USD
#W:userdata
#W:UTF
#W:valgrind
#W:Vanem
#W:vararg
#W:VC
#W:vcpkg
#W:VERIFYRESULT
#W:Viktor
#W:VMware
#W:vt
#W:vtls
#W:Warta
#W:WAV
#W:WB
#W:web page
#W:WebSocket
#W:whitespace
#W:winbuild
#W:WinSock
#W:WinSSL
#W:Wireshark
#W:wolfSSH
#W:wolfSSL
#W:www
#W:xdigit
#W:Xilinx
#W:XYZ
#W:Youtube
#W:Zakrzewski
#W:Zitzmann
#W:zlib
#W:zsh
#W:SPDX
#W:al
#W:et
#W:fuzzer
#W:Preprocessing
#W:CodeQL
#W:LGTM
#W:appveyor
#W:buildbot
#W:codeql
#W:deepcode
#W:macos
#W:musedev
#W:winssl
