# Copyright (C) 2022 Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: spell
on:
  push:
    branches:
    - master
    paths:
    - '**.md'
  pull_request:
    branches:
    - master

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: convert .3 man pages to markdown
      run: git ls-files '*.3' | sed 's/.3//' | xargs -n1 -I OO pandoc OO.3 -o OO.md

    - name: convert .1 man pages to markdown
      run: git ls-files '*.1' | sed 's/.1//' | xargs -n1 -I OO pandoc OO.1 -o OO.md

    - name: Check Spelling
      uses: UnicornGlobal/spellcheck-github-actions@master
